<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Migrations\**" />
    <Compile Remove="Fabricas\**" />
    <EmbeddedResource Remove="Fabricas\**" />
    <None Remove="Fabricas\**" />
  </ItemGroup>

  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <None Remove="EmailTemplates\external-user-email-update.html" />
    <None Remove="EmailTemplates\temporary-code-alt.html" />
    <None Remove="EmailTemplates\external-user-access.html" />
    <None Remove="EmailTemplates\role-created.html" />
    <None Remove="EmailTemplates\role-edited.html" />
    <None Remove="EmailTemplates\user-created.html" />
    <None Remove="EmailTemplates\temporary-code.html" />
    <None Remove="EmailTemplates\access-denied.html" />
    <None Remove="EmailTemplates\verify-email.html" />
    <None Remove="EmailTemplates\email-layout.html" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="EmailTemplates\role-edited.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="EmailTemplates\role-created.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="EmailTemplates\access-denied.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="EmailTemplates\email-layout.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="EmailTemplates\verify-email.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="EmailTemplates\temporary-code.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="EmailTemplates\user-created.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.Specification.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.2" />
    <PackageReference Include="Stubble.Core" Version="1.10.8" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.2.1" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="EmailTemplates\temporary-code-alt.html" />
  </ItemGroup>

</Project>
